
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - movieflix-network

  app:
    build: ./app
    ports:
      - "3000"
    environment:
      - DB_HOST=mysql  # ✅ Garantir que use o nome do serviço
      - DB_USER=movieflix_user
      - DB_PASSWORD=movieflix123
      - DB_NAME=movieflix
      - NODE_ENV=development
    depends_on:
      mysql:
        condition: service_healthy  # ✅ Esperar MySQL ficar saudável
    networks:
      - movieflix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=movieflix
      - MYSQL_USER=movieflix_user
      - MYSQL_PASSWORD=movieflix123
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - movieflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "movieflix_user", "-pmovieflix123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  movieflix-network:
    driver: bridge