services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - movieflix-network

  app:
    build: ./app
    ports:
      - "3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_NAME=${DB_NAME}  
    depends_on:
      - mysql
    networks:
      - movieflix-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}  
      - MYSQL_DATABASE=${DB_NAME}  
      - MYSQL_USER=${DB_USER} 
      - MYSQL_PASSWORD=${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - movieflix-network

volumes:
  mysql_data:

networks:
  movieflix-network:
    driver: bridge